version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - modernize
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: exported
          disabled: true
        - name: unused-parameter
          disabled: true
  exclusions:
    rules:
      - path: server/configuration.go
        linters:
          - unused
      - path: _test\.go
        linters:
          - bodyclose

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - github.com/mattermost/mattermost-plugin-channel-export
