version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@0.1.0

workflows:
  version: 2
  ci:
    jobs:
      - plugin-ci/lint
      - plugin-ci/test
      - plugin-ci/build
      - plugin-ci/deploy-release:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
      - plugin-ci/deploy-release-github:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
        context: matterbuild-github-token
        requires:
          - plugin-ci/lint
          - plugin-ci/test
          - plugin-ci/build
          - plugin-ci/deploy-release
