version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@0.1.0

workflows:
  test:
    jobs:
      - plugin-ci/lint
      - plugin-ci/test
      - plugin-ci/build
      - plugin-ci/deploy-release:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
        requires:
          - plugin-ci/lint
          - plugin-ci/test
          - plugin-ci/build
